keys:
  - &puter ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAgevajch6O5ZQYWubHgaRZPnhrFM937mjUQO4gT+Bnr user@bluefin
  - &larstop2 age1j7v73aqlq3ztnhfuwlu6gjant5yqk58sleq9ayc9z0rj2ng2ls8qp8tket
  - &muehml age18xluezp2cypkscd80w4hv0vzgeyqu2uvqdxn3ta4uyphvvad8dqqrrvmnp
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *larstop2
      - *muehml
      - *puter
