name: update-flake-lock
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 5 * * *' # runs weekly on Sunday at 00:00

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v24
        with:
          pr-title: "Update flake.lock" # Title of PR to be created
          pr-labels: |                  # Labels to be set on the PR
            dependencies
            automated
          pr-assignees: BurNiinTRee
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
      - name: Auto-Merge PR
        run: |
          gh pr merge --auto ${{ steps.update.outputs.pull-request-number }}
